### ISSUE TITLE
Menu Button

### ISSUE THREAD

**Issue by raji1201** [raji1201/Movie-Recommendation-System#1]
Menu button should be on the right end of the navbar. Can someone try fixing it please?
![fix](https://user-images.githubusercontent.com/23444595/30794911-eb858450-a198-11e7-886c-09473b8dd1b9.PNG)

**Comment by manojp1902** [comment]
![screen shot 2017-10-30 at 7 40 07 pm](https://user-images.githubusercontent.com/9829521/32200868-397a4c5e-bdaa-11e7-88a4-5ad06cfaafd8.png)


Search bar included in the navbar block was the issue. Made it another form element.
