### ISSUE TITLE
Not able to view menu for login on homepage

### ISSUE THREAD

**Issue by manojp1902** [raji1201/Movie-Recommendation-System#11]
The homepage is not rendering properly
Steps to reproduce:
1.run ngserve
2. open localhost:4200 on browser.
![screen shot 2017-10-16 at 7 33 30 pm](https://user-images.githubusercontent.com/9829521/31639893-4a55d25c-b2a9-11e7-8e55-3c8f1d587259.png)

**Comment by raji1201** [comment]
I tried running it and it works perfectly. Sync the master branch with your branch.

**Comment by manojp1902** [comment]
Issue Resolved. Was referencing old material files. Solved after reinstalling angular module.
