### ISSUE TITLE
Add movies to DB

### ISSUE THREAD

**Issue by raji1201** [raji1201/Movie-Recommendation-System#20]
Add movies to elasticsearch DB and MySQL DB.
Add ratings to MySQL DB.

**Comment by raji1201** [comment]
Movies added to MySQL DB.
Further action : Add movies to Elasticsearch

**Comment by Taaji** [comment]
The same database of movies as the one currently in MySQL right?

**Comment by raji1201** [comment]
Yes, same data, same attributes.

**Comment by raji1201** [comment]
Done!
