### ISSUE TITLE
Movie Review Page

### ISSUE THREAD

**Issue by raji1201** [raji1201/Movie-Recommendation-System#4]
Create template for movie review page

**Comment by manojp1902** [comment]
created a basic template

![screen shot 2017-10-16 at 3 37 01 pm](https://user-images.githubusercontent.com/9829521/31631536-f30ebb88-b287-11e7-8f19-e0aff68bc88f.png)

**Comment by raji1201** [comment]
Looks good! Send in a pull req. I'm closing this issue.
