### ISSUE TITLE
Front end documentation

### ISSUE THREAD

**Issue by raji1201** [raji1201/Movie-Recommendation-System#49]
Document all front end code. Add comments

**Comment by raji1201** [comment]
Work split up : 
Raji - User Service, Login, Movie Review, Navbar, Profile, TRM, E2E tests.
Manoj - Signup, Home, Movies Watched, Search Results, Unit tests.

**Comment by raji1201** [comment]
Completed documentation for User Service, Login, Movie Review, Navbar, Profile, TRM, E2E tests.

**Comment by raji1201** [comment]
Manoj, ETA on this, please?

**Comment by manojp1902** [comment]
Completed the documentation for Signup, Home, Movies Watched, Search Results.
Will close once review is done and merged onto /master

**Comment by raji1201** [comment]
Documentation for Signup, Home, Movies Watched, Search Results done by Manoj.
Manoj is working on documenting unit tests.

**Comment by manojp1902** [comment]
Ready for review

**Comment by raji1201** [comment]
Requested changes on review.

**Comment by raji1201** [comment]
Done. Merged to master.
