### ISSUE TITLE
Data formatting from backend to frontend

### ISSUE THREAD

**Issue by kavindesai** [raji1201/Movie-Recommendation-System#51]
Data extracted from query when sent in JSON object to frontend gets formatted if there are any single quotes.
Eg. An offer you can't refuse becomes An offer you can\'t refuse.

Check on frontend while displaying does it revert back to intended format or stays the same.

**Comment by raji1201** [comment]
Kavin, what needs to be done for this?

**Comment by kavindesai** [comment]
I ran the solution you gave and I read up on it and tweaked it a bit and it works. Pushed the changes in last update.

**Comment by raji1201** [comment]
Great!
